name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: |
        poetry install

    - name: Run tests (excluding real LLM tests)
      env:
        ENABLE_REAL_LLM_TESTS: 0
        PYTHONPATH: .
      run: |
        poetry run pytest tests/ -v --strict-markers -m "not local_only and not real_llm" --cov=pinocchio --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: |
        poetry install

    - name: Run linting
      run: |
        poetry run flake8 pinocchio/ tests/ --max-line-length=150 --ignore=W291,W293,E203,E501,W503,D200,D401,D400,D202,C901,D205,E402,F401,F841,E712 --max-complexity=25 --exclude=.git,__pycache__,build,dist
        poetry run black --check pinocchio/ tests/
        poetry run isort --check-only pinocchio/ tests/
        poetry run mypy pinocchio/ --ignore-missing-imports
